version: '3'

services:
  app:
    image: maven:3.9-eclipse-temurin-17
    container_name: my-app-8082
    ports:
      - "8082:8082"
    volumes:
      - ./:/app
    working_dir: /app
    # ========================= 关键修改 START =========================
    # 从 .env 文件或当前shell环境中读取环境变量
    environment:
      # 语法 `${VAR_NAME}` 会让 Docker Compose 查找名为 VAR_NAME 的环境变量
      - GITEE_PACKAGE_PEM_RSA_PRIVATE_KEY=${GITEE_PACKAGE_PEM_RSA_PRIVATE_KEY}
    # ========================= 关键修改 END ===========================
    command: java -Duser.timezone=Asia/Shanghai -jar app.jar