version: '3.8'

services:
  app:
    build: .
    container_name: my-app-8082
    ports:
      - "8080:8080"
      - "8082:8082"
    volumes:
      # 1. 将当前目录挂载到容器的 /app 目录 (保持不变)
      - ./app.jar:/app/app.jar
      - ./application.properties:/app/application.properties

      # 2. 挂载 Maven 配置文件
      - ./settings.xml:/root/.m2/settings.xml

      # ✅ 修改点：挂载 Maven 本地仓库目录
      - ./repository/:/root/.m2/repository

      # SSH 配置挂载（如用于访问私有仓库）
      - ./.ssh:/root/.ssh

    working_dir: /app

    environment:
      - GITEE_PACKAGE_PEM_RSA_PRIVATE_KEY=${GITEE_PACKAGE_PEM_RSA_PRIVATE_KEY}

    command: java -Duser.timezone=Asia/Shanghai -jar app.jar
