version: '3.8'

services:
  app:
    build: .
    container_name: my-app-8082
    ports:
      - "8082:8082"
    volumes:
      # 1. 将当前目录挂载到容器的 /app 目录 (保持不变)
      - ./:/app

      # 2. 【核心修改】将本地的 settings.xml 挂载到容器内 Maven 的配置目录
      #    这会覆盖镜像中原有的 settings.xml 文件。
      #    源路径: ./settings.xml (当前目录下的 settings.xml)
      #    目标路径: /root/.m2/settings.xml (容器内 Maven 的标准配置路径)
      - ./settings.xml:/root/.m2/settings.xml

    working_dir: /app # 明确设置工作目录是个好习惯

    environment:
      - GITEE_PACKAGE_PEM_RSA_PRIVATE_KEY=${GITEE_PACKAGE_PEM_RSA_PRIVATE_KEY}

    # 关键修改：修改启动命令，实现 "先编译，后运行"
    # 使用 sh -c 来执行一连串的 shell 命令
    # 直接启动java应用，因为maven已经内置在镜像里了
    command: java -Duser.timezone=Asia/Shanghai -jar app.jar